apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ required "mongodb auth.rootPassword is required" .Values.auth.rootPassword | b64enc | quote }}
