{{- if and (index .Values.global "gms-api").enabled (index .Values.global "mongodb").enabled (not (dig "mongodb" "externalDatabase" "enabled" false (.Values | toYaml | fromYaml))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gms-api-mongodb-auth
  labels:
    app.kubernetes.io/name: gms-api-mongodb-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  mongodb-username: {{ required "mongodb.auth.username is required for gms-api" .Values.mongodb.auth.username | quote }}
  mongodb-password: {{ required "mongodb.auth.password is required for gms-api" .Values.mongodb.auth.password | quote }}
{{- end }}
