{{- if .Values.global.tls.createSecrets }}
---
# root-ca secret - Required by historian-svc
apiVersion: v1
kind: Secret
metadata:
  name: root-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opendso.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: Opaque
data:
  ca.pem: {{ .Values.global.tls.caCert | b64enc | quote }}

---
# server-cert secret - Required by historian-svc
apiVersion: v1
kind: Secret
metadata:
  name: server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opendso.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.tls.serverCert | b64enc | quote }}
  tls.key: {{ .Values.global.tls.serverKey | b64enc | quote }}

---
# server-key secret - Required by historian-svc
apiVersion: v1
kind: Secret
metadata:
  name: server-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opendso.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.tls.serverCert | b64enc | quote }}
  tls.key: {{ .Values.global.tls.serverKey | b64enc | quote }}

{{- end }}
