{{- if .Values.config.mongodb.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gms-api.fullname" . }}-mongodb
  labels:
    {{- include "gms-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-username: {{ .Values.config.mongodb.username | quote }}
  mongodb-password: {{ .Values.config.mongodb.password | quote }}
{{- end }}
