apiVersion: v2
name: der-dispatch-app
description: DER Dispatch Application for OpenDSO
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: OpenDSO Team
    email: info@openenergysolutions.com
