apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  keycloak.conf: |
    # Basic settings
    http-enabled={{ .Values.config.httpEnabled }}
    http-port={{ .Values.config.httpPort }}
    https-port={{ .Values.config.httpsPort }}
    {{- if .Values.config.hostname }}
    hostname={{ .Values.config.hostname }}
    {{- end }}

    {{- if .Values.config.httpsEnabled }}
    # HTTPS settings
    https-certificate-file={{ .Values.config.httpsCertFile }}
    https-certificate-key-file={{ .Values.config.httpsKeyFile }}
    {{- end }}

    {{- if .Values.config.database.enabled }}
    # Database
    db={{ .Values.config.database.vendor }}
    db-url-host={{ .Values.config.database.host }}
    db-url-port={{ .Values.config.database.port }}
    db-url-database={{ .Values.config.database.name }}
    db-username={{ .Values.config.database.username }}
    db-password={{ required "keycloak database password is required when keycloak.config.database.enabled=true" .Values.config.database.password }}
    {{- end }}

    # Logging
    log-level={{ .Values.config.logLevel }}
