apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-svc
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.httpPort }}
      targetPort: {{ .Values.config.httpPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
    {{- if .Values.config.httpsEnabled }}
    - port: {{ .Values.config.httpsPort }}
      targetPort: {{ .Values.config.httpsPort }}
      protocol: TCP
      name: https
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.https }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
