apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cvr-genetic-algorithm-svc.fullname" . }}
  labels:
    {{- include "cvr-genetic-algorithm-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cvr-genetic-algorithm-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cvr-genetic-algorithm-svc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "cvr-genetic-algorithm-svc.image" (dict "imageRoot" .Values.global.images.cvrGeneticAlgorithmSvc "registry" .Values.global.imageRegistry) | quote }}
          imagePullPolicy: {{ .Values.global.images.cvrGeneticAlgorithmSvc.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: dss-files
              mountPath: /dss
              readOnly: true
          resources:
            {{- include "opendso.resources" (dict "root" . "category" "services" "explicit" .Values.resources) | nindent 12 }}
      volumes:
        - name: dss-files
          configMap:
            name: {{ .Values.siteConfigMap | default (printf "%s-cvr-genetic-algorithm-svc-site-config" .Release.Name) }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
