apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openfmb-event-creator-app.fullname" . }}
  labels:
    {{- include "openfmb-event-creator-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openfmb-event-creator-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openfmb-event-creator-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "openfmb-event-creator-app.image" (dict "imageRoot" .Values.global.images.openfmbEventCreatorApp "registry" .Values.global.imageRegistry) | quote }}
          imagePullPolicy: {{ .Values.global.images.openfmbEventCreatorApp.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: environment
              mountPath: /usr/share/nginx/html/config
              readOnly: true
            - name: config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            {{- if .Values.tls.enabled }}
            - name: cert-file
              mountPath: /etc/nginx/certs/server-cert.pem
              subPath: server-cert.pem
              readOnly: true
            - name: key-file
              mountPath: /etc/nginx/certs/server-key.pem
              subPath: server-key.pem
              readOnly: true
            {{- end }}
          resources:
            {{- include "opendso.resources" (dict "root" . "category" "frontends" "explicit" .Values.resources) | nindent 12 }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.livenessProbe.httpGet }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            {{- else if .Values.livenessProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.livenessProbe.tcpSocket.port }}
            {{- else if .Values.livenessProbe.exec }}
            exec:
              command:
                {{- toYaml .Values.livenessProbe.exec.command | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.readinessProbe.httpGet }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            {{- else if .Values.readinessProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.readinessProbe.tcpSocket.port }}
            {{- else if .Values.readinessProbe.exec }}
            exec:
              command:
                {{- toYaml .Values.readinessProbe.exec.command | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openfmb-event-creator-app.fullname" . }}-nginx
        - name: environment
          configMap:
            name: {{ .Release.Name }}-frontend-environment
        {{- if .Values.tls.enabled }}
        - name: cert-file
          secret:
            secretName: {{ .Values.tls.certSecret }}
        - name: key-file
          secret:
            secretName: {{ .Values.tls.keySecret }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
