apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ods-svc.fullname" . }}
  labels:
    {{- include "ods-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ods-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ods-svc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "ods-svc.image" (dict "imageRoot" .Values.global.images.odsSvc "registry" .Values.global.imageRegistry) | quote }}
          imagePullPolicy: {{ .Values.global.images.odsSvc.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-ods-svc-keycloak-env" .Release.Name }}
                optional: true
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- include "opendso.resources" (dict "root" . "category" "services" "explicit" .Values.resources) | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.siteConfigMap | default (printf "%s-ods-svc-site-config" .Release.Name) }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
