apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ess-tester-app.fullname" . }}-nginx
  labels:
    {{- include "ess-tester-app.labels" . | nindent 4 }}
data:
  default.conf: |
{{ include "opendso.frontend.nginx" . | indent 4 }}
