{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "topology-genesis.fullname" . }}
  labels:
    {{- include "topology-genesis.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | default .Values.global.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
