{{- if dig "keycloak-db" "enabled" false .Values.global }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-db.fullname" . }}-secret
  labels:
    {{- include "keycloak-db.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "keycloak-db auth.password is required when keycloak-db is enabled" .Values.auth.password | b64enc | quote }}
{{- end }}
