replicaCount: 1

image:
  repository: oesinc/topology-nodes
  pullPolicy: IfNotPresent
  tag: "adaa70e0"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env:
  PLATFORM_NATS_SERVICE: ""
  PLATFORM_NATS_PORT: "4222"

args:
  - "-c"
  - "/resources/config.yml"

# Service configuration
config:
  nats:
    server: ""
    tls:
      enabled: false
      certFile: "/certs/client-cert.pem"
      keyFile: "/certs/client-key.pem"
      caFile: "/certs/ca.pem"
  logging:
    level: "info"
  region:
    id: "region-1"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
