apiVersion: v2
name: cvr-openfmb-services-svc
description: OpenFMB Services for OpenDSO
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: OpenDSO Team
    email: info@openenergysolutions.com
