# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
# db=postgres

# The username of the database user.
# db-username=keycloak

# The password of the database user.
# db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
# db-url=jdbc:postgresql://keycloak-db:5432/

# Observability

# If the server should expose healthcheck endpoints.
health-enabled=true

# If the server should expose metrics endpoints.
metrics-enabled=true

# HTTP
# Keycloak runs behind nginx ingress, which terminates TLS.
# http-enabled allows Keycloak to accept HTTP from the proxy.
http-enabled=true
