{{- if and (not .Values.externalDatabase.enabled) (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citus-db.fullname" . }}-secret
  labels:
    {{- include "citus-db.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.auth.password | default (include "opendso.citusDbPassword" .) | b64enc | quote }}
{{- end }}
