#!/bin/bash
#
# Custom deployer script for OpenDSO GCP Marketplace.
#
# Extends the standard deployer_helm flow with NATS NKey generation:
#   1. Generates fresh NKey pairs (account, user, curve/xkey)
#   2. Creates the nats-auth-keys Kubernetes secret with the private seeds
#   3. Writes a temporary Helm values overlay with the derived public keys
#   4. Runs helm upgrade --install using the framework-generated user values
#
# Environment variables injected by GCP Marketplace deployer framework:
#   APP_INSTANCE_NAME      — Helm release name
#   NAMESPACE              — target namespace
#   REGISTRY               — marketplace registry (from REGISTRY type in schema.yaml)
#   IMAGE_<KEY>            — per-image refs (from images section in schema.yaml)
#   /data/user/values.yaml — all schema.yaml property values as nested Helm values
#                            (generated by the framework from the user's Marketplace UI input)
#
# NOTE: Do NOT reconstruct --set flags from env vars for schema properties.
#       Use /data/user/values.yaml instead — this is the authoritative source.
#
# ---------------------------------------------------------------------------
# ASSUMPTIONS — this script does NOT handle:
#
#   - GKE cluster creation (must exist before deployer runs)
#   - nginx ingress controller (must be installed in the cluster)
#   - cert-manager / TLS certificate creation (must exist as <release>-tls-secret)
#   - DNS configuration (wildcard *.domain must resolve to ingress LoadBalancer IP)
#   - Image pull authentication (handled by GKE node service account / Workload Identity)
#
# NOTE: Keycloak client provisioning is handled automatically by this script
#   (step 3b). Client secrets are generated and injected into the realm JSON
#   before Helm runs, so Keycloak imports pre-populated secrets on first boot
#   and all *-keycloak-env Kubernetes secrets are created before services start.
#   No post-install provisioning step is required.
# ---------------------------------------------------------------------------

set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OpenDSO GCP Marketplace Deployer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

CHART_DIR="/data/chart"
USER_VALUES="${USER_VALUES:-/data/user/values.yaml}"
NATS_AUTH_VALUES=$(mktemp /tmp/nats-auth-values.XXXXXX.yaml)
NATS_KEYS_SECRET="${APP_INSTANCE_NAME}-nats-auth-keys"

# Derive domain from user values for computed --set flags
DOMAIN=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('global', {}).get('domain', ''))
" 2>/dev/null || echo "")

# ---------------------------------------------------------------------------
# 1. Generate NATS NKeys
# ---------------------------------------------------------------------------
echo "[1/3] Generating NATS NKeys..."

ACCOUNT_SEED=$(nk -gen account)
USER_SEED=$(nk -gen user)
XKEY_SEED=$(nk -gen curve)

ACCOUNT_PUB=$(echo "$ACCOUNT_SEED" | nk -inkey /dev/stdin -pubout)
USER_PUB=$(echo "$USER_SEED"       | nk -inkey /dev/stdin -pubout)
XKEY_PUB=$(echo "$XKEY_SEED"      | nk -inkey /dev/stdin -pubout)

echo "  Account public key: $ACCOUNT_PUB"
echo "  User public key:    $USER_PUB"
echo "  XKey public key:    $XKEY_PUB"

# ---------------------------------------------------------------------------
# 2. Create/update the nats-auth-keys Kubernetes secret (private seeds)
# ---------------------------------------------------------------------------
echo ""
echo "[2/3] Creating nats-auth-keys secret in namespace '$NAMESPACE'..."

kubectl create secret generic "$NATS_KEYS_SECRET" \
    --namespace="$NAMESPACE" \
    --from-literal=account.nk="$ACCOUNT_SEED" \
    --from-literal=user.nk="$USER_SEED" \
    --from-literal=xkey.xk="$XKEY_SEED" \
    --dry-run=client -o yaml | kubectl apply -f -

echo "  Secret '$NATS_KEYS_SECRET' applied."

# ---------------------------------------------------------------------------
# 3. Write temporary Helm values overlay with derived public keys
# ---------------------------------------------------------------------------
cat > "$NATS_AUTH_VALUES" << EOF
# Auto-generated at deploy time by deployer/deploy.sh — do not edit
nats:
  authCallout:
    enabled: true
    issuer: ${ACCOUNT_PUB}
    authUser: ${USER_PUB}
    xkey: ${XKEY_PUB}

global:
  nats-auth-svc:
    enabled: true

nats-auth-svc:
  natsKeysSecret: "${NATS_KEYS_SECRET}"
EOF

# ---------------------------------------------------------------------------
# 3b. Inject Keycloak client secrets into realm JSON and create K8s secrets
#
# Generates a UUID secret per NATS service client, writes them into the realm
# JSON (so Keycloak imports pre-populated secrets on first boot), and creates
# <release>-<client>-keycloak-env Kubernetes secrets so services can start
# immediately after Helm without any post-install provisioning step.
# ---------------------------------------------------------------------------
echo ""
echo "[3b/3] Injecting Keycloak client secrets..."

SITE=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('global', {}).get('site', 'ieee13'))
" 2>/dev/null || echo "ieee13")

REALM_FILE="${CHART_DIR}/configs/${SITE}/keycloak/realm/oes-realm.json"
KC_CLUSTER_URL="http://${APP_INSTANCE_NAME}-keycloak-svc:8080/realms/oes"

python3 - "${REALM_FILE}" "${APP_INSTANCE_NAME}" "${NAMESPACE}" "${KC_CLUSTER_URL}" << 'PYEOF'
import json, uuid, subprocess, sys, re

realm_file, release_name, namespace, kc_url = sys.argv[1:]

with open(realm_file) as f:
    content = f.read()

# Find all REPLACE_SECRET_<client-id> placeholders
placeholders = re.findall(r'REPLACE_SECRET_([\w-]+)', content)
secrets = {name: str(uuid.uuid4()) for name in dict.fromkeys(placeholders)}

# Replace placeholders with generated UUIDs
for name, secret in secrets.items():
    content = content.replace(f'REPLACE_SECRET_{name}', secret)

with open(realm_file, 'w') as f:
    f.write(content)

print(f"  Patched {len(secrets)} client secrets in realm JSON")

# Create K8s secrets for each client
errors = 0
for name, secret in secrets.items():
    secret_name = f"{release_name}-{name}-keycloak-env"
    render = subprocess.run([
        "kubectl", "create", "secret", "generic", secret_name,
        "--namespace", namespace,
        f"--from-literal=KEYCLOAK_URL={kc_url}",
        f"--from-literal=KEYCLOAK_CLIENT_ID={name}",
        f"--from-literal=KEYCLOAK_CLIENT_SECRET={secret}",
        "--dry-run=client", "-o", "yaml",
    ], capture_output=True, text=True)
    if render.returncode != 0:
        print(f"  WARNING: render failed for {secret_name}: {render.stderr}", file=sys.stderr)
        errors += 1
        continue
    apply = subprocess.run(
        ["kubectl", "apply", "-f", "-"],
        input=render.stdout, capture_output=True, text=True,
    )
    if apply.returncode != 0:
        print(f"  WARNING: apply failed for {secret_name}: {apply.stderr}", file=sys.stderr)
        errors += 1
    else:
        print(f"  Applied {secret_name}")

if errors:
    print(f"  WARNING: {errors} secret(s) failed — check output above", file=sys.stderr)
PYEOF

# ---------------------------------------------------------------------------
# 4. Deploy via Helm
#
# Values precedence (last wins):
#   values-gcp.yaml        — GCP-specific defaults
#   /data/user/values.yaml — user inputs from Marketplace UI (schema.yaml properties)
#   $NATS_AUTH_VALUES      — generated NKey public keys
#   --set overrides        — release-name-dependent values that can't be in values files
# ---------------------------------------------------------------------------
echo ""
echo "[3/3] Running helm upgrade --install..."

helm upgrade --install "$APP_INSTANCE_NAME" "$CHART_DIR" \
    --namespace "$NAMESPACE" \
    --wait \
    --timeout 15m \
    -f "$CHART_DIR/values-gcp.yaml" \
    -f "$USER_VALUES" \
    -f "$NATS_AUTH_VALUES" \
    --set global.keycloak.internalUrl="http://${APP_INSTANCE_NAME}-keycloak-svc:8080" \
    --set global.environment.apiUrl="https://api.${DOMAIN}" \
    --set global.keycloak.url="https://keycloak.${DOMAIN}" \
    --set keycloak.config.hostname="keycloak.${DOMAIN}" \
    --set ingress.tls.secretName="${APP_INSTANCE_NAME}-tls-secret" \
    --set nats.tls.secretName="${APP_INSTANCE_NAME}-tls-secret" \
    --set mongodb.tls.existingSecret="${APP_INSTANCE_NAME}-mongodb-tls" \
    --set grafana.admin.existingSecret="${APP_INSTANCE_NAME}-grafana-credentials" \
    --set "grafana.envValueFrom.CITUS_PASSWORD.secretKeyRef.name=${APP_INSTANCE_NAME}-grafana-credentials" \
    --set "grafana.envValueFrom.OPENDSO_APPS_DB_PASSWORD.secretKeyRef.name=${APP_INSTANCE_NAME}-grafana-credentials" \
    --set global.gcpMarketplace=true

echo ""
echo "OpenDSO deployed successfully as release '$APP_INSTANCE_NAME'."

# Clean up temp file
rm -f "$NATS_AUTH_VALUES"
