#!/bin/bash
#
# Custom deployer script for OpenDSO GCP Marketplace.
#
# Extends the standard deployer_helm flow with NATS NKey generation:
#   1. Generates fresh NKey pairs (account, user, curve/xkey)
#   2. Creates the nats-auth-keys Kubernetes secret with the private seeds
#   3. Writes a temporary Helm values overlay with the derived public keys
#   4. Runs helm upgrade --install using the framework-generated user values
#
# Environment variables injected by GCP Marketplace deployer framework:
#   APP_INSTANCE_NAME      — Helm release name
#   NAMESPACE              — target namespace
#   REGISTRY               — marketplace registry (from REGISTRY type in schema.yaml)
#   IMAGE_<KEY>            — per-image refs (from images section in schema.yaml)
#   /data/user/values.yaml — all schema.yaml property values as nested Helm values
#                            (generated by the framework from the user's Marketplace UI input)
#
# NOTE: Do NOT reconstruct --set flags from env vars for schema properties.
#       Use /data/user/values.yaml instead — this is the authoritative source.
#
# ---------------------------------------------------------------------------
# ASSUMPTIONS — this script does NOT handle:
#
#   - GKE cluster creation (must exist before deployer runs)
#   - nginx ingress controller (must be installed in the cluster)
#   - cert-manager / TLS certificate creation (must exist as <release>-tls-secret)
#   - DNS configuration (wildcard *.domain must resolve to ingress LoadBalancer IP)
#   - Image pull authentication (handled by GKE node service account / Workload Identity)
#
# NOTE: Keycloak client provisioning is handled automatically by this script
#   (step 3b). Client secrets are generated and injected into the realm JSON
#   before Helm runs, so Keycloak imports pre-populated secrets on first boot
#   and all *-keycloak-env Kubernetes secrets are created before services start.
#   No post-install provisioning step is required.
# ---------------------------------------------------------------------------

set -euo pipefail

# Resolve NAME/NAMESPACE from the Marketplace config (injected via /data/values.yaml).
# The deployer_helm base image sets these in its own deploy.sh; we must do it ourselves.
APP_INSTANCE_NAME="$(/bin/print_config.py --xtype NAME --values_mode raw)"
NAMESPACE="$(/bin/print_config.py --xtype NAMESPACE --values_mode raw)"
NAME="$APP_INSTANCE_NAME"
export APP_INSTANCE_NAME NAMESPACE NAME

# Fail-safe: mark the Application as Failed on any unexpected exit.
handle_failure() {
  code=$?
  patch_assembly_phase.sh --status="Failed" || true
  exit $code
}
trap "handle_failure" EXIT

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OpenDSO GCP Marketplace Deployer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Extract chart from tarball (deployer_helm base image does this in create_manifests.sh;
# since we bypass that, we do it here before calling helm upgrade).
mkdir -p /data/extracted/chart
tar -xzf /data/chart/chart.tar.gz -C /data/extracted/chart

CHART_DIR="/data/extracted/chart/chart"

# Generate user values in nested YAML format for helm -f.
USER_VALUES=$(mktemp /tmp/user-values.XXXXXX.yaml)
/bin/print_config.py --output=yaml --values_mode raw > "$USER_VALUES"

NATS_AUTH_VALUES=$(mktemp /tmp/nats-auth-values.XXXXXX.yaml)
NATS_KEYS_SECRET="${APP_INSTANCE_NAME}-nats-auth-keys"

# Derive domain and imageRegistry from user values for computed --set flags
DOMAIN=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('global', {}).get('domain', ''))
" 2>/dev/null || echo "")

IMAGE_REGISTRY=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('global', {}).get('imageRegistry', ''))
" 2>/dev/null || echo "")

# Extract license keys from user values (stored in a K8s Secret, never in Helm values)
LICENSE_KEY=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('license', {}).get('key', ''))
" 2>/dev/null || echo "")

INSTALLATION_KEY=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('installation', {}).get('key', ''))
" 2>/dev/null || echo "")

# Cluster ID for license environment name (kube-system namespace UID is unique per cluster)
CLUSTER_ID=$(kubectl get namespace kube-system -o jsonpath='{.metadata.uid}' 2>/dev/null || echo "unknown")

# ---------------------------------------------------------------------------
# 1. Generate NATS NKeys (reuse existing on re-runs to avoid NATS reconfiguration)
# ---------------------------------------------------------------------------
echo "[1/3] Generating NATS NKeys..."

# Reuse existing seeds if the secret already exists so NATS and nats-auth-svc
# continue to use the same keys across deployer re-runs.
if kubectl get secret "$NATS_KEYS_SECRET" --namespace="$NAMESPACE" >/dev/null 2>&1; then
    echo "  Reusing existing NKeys from secret '$NATS_KEYS_SECRET'..."
    ACCOUNT_SEED=$(kubectl get secret "$NATS_KEYS_SECRET" --namespace="$NAMESPACE" \
        -o jsonpath='{.data.account\.nk}' | base64 -d)
    USER_SEED=$(kubectl get secret "$NATS_KEYS_SECRET" --namespace="$NAMESPACE" \
        -o jsonpath='{.data.user\.nk}' | base64 -d)
    XKEY_SEED=$(kubectl get secret "$NATS_KEYS_SECRET" --namespace="$NAMESPACE" \
        -o jsonpath='{.data.xkey\.xk}' | base64 -d)
else
    echo "  Generating fresh NKeys..."
    ACCOUNT_SEED=$(nk -gen account)
    USER_SEED=$(nk -gen user)
    XKEY_SEED=$(nk -gen curve)
fi

ACCOUNT_PUB=$(echo "$ACCOUNT_SEED" | nk -inkey /dev/stdin -pubout)
USER_PUB=$(echo "$USER_SEED"       | nk -inkey /dev/stdin -pubout)
XKEY_PUB=$(echo "$XKEY_SEED"      | nk -inkey /dev/stdin -pubout)

echo "  Account public key: $ACCOUNT_PUB"
echo "  User public key:    $USER_PUB"
echo "  XKey public key:    $XKEY_PUB"

# ---------------------------------------------------------------------------
# 2. Create/update the nats-auth-keys Kubernetes secret (private seeds)
# ---------------------------------------------------------------------------
echo ""
echo "[2/3] Creating nats-auth-keys secret in namespace '$NAMESPACE'..."

kubectl create secret generic "$NATS_KEYS_SECRET" \
    --namespace="$NAMESPACE" \
    --from-literal=account.nk="$ACCOUNT_SEED" \
    --from-literal=user.nk="$USER_SEED" \
    --from-literal=xkey.xk="$XKEY_SEED" \
    --dry-run=client -o yaml | kubectl apply -f -

echo "  Secret '$NATS_KEYS_SECRET' applied."

# ---------------------------------------------------------------------------
# 3. Write temporary Helm values overlay with derived public keys
# ---------------------------------------------------------------------------
cat > "$NATS_AUTH_VALUES" << EOF
# Auto-generated at deploy time by deployer/deploy.sh — do not edit
nats:
  authCallout:
    enabled: true
    issuer: ${ACCOUNT_PUB}
    authUser: ${USER_PUB}
    xkey: ${XKEY_PUB}

global:
  nats-auth-svc:
    enabled: true
  # GCP Marketplace: node SA has Artifact Registry reader access — no pull secret needed
  imagePullSecrets: []
  # topology-genesis ConfigMap is pre-created via kubectl --server-side in step 3a
  # (cim.xml is 367KB — exceeds the 262KB Kubernetes annotation limit for client-side apply).
  # Setting externalConfigMap=true tells the Helm template to skip creating it.
  topology-genesis:
    externalConfigMap: true

nats-auth-svc:
  natsKeysSecret: "${NATS_KEYS_SECRET}"
EOF

# Resolve site name (used by both step 3a and 3b below)
SITE=$(python3 -c "
import sys, yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f)
print(v.get('global', {}).get('site', 'ieee13'))
" 2>/dev/null || echo "ieee13")

# ---------------------------------------------------------------------------
# 3a. Pre-create topology-genesis ConfigMap via server-side apply
#
# cim.xml is 367KB — larger than the 262KB hard limit Kubernetes enforces on
# annotation values. kubectl apply (client-side) stores the entire resource as
# the last-applied-configuration annotation, so it fails. Server-side apply
# (--server-side) does not store that annotation; it uses field managers instead.
#
# The Helm template skips creating this ConfigMap when
# global.topology-genesis.externalConfigMap=true (see site-configmaps.yaml).
# ---------------------------------------------------------------------------
echo ""
echo "[3a/3] Pre-creating topology-genesis ConfigMap (server-side apply)..."

kubectl create configmap "${APP_INSTANCE_NAME}-topology-genesis-site-config" \
    --namespace="$NAMESPACE" \
    --from-file=cim.xml="${CHART_DIR}/configs/${SITE}/topology-genesis/cim.xml" \
    --from-file=cimex.config="${CHART_DIR}/configs/${SITE}/topology-genesis/cimex.config" \
    --dry-run=client -o yaml \
  | kubectl apply --server-side --field-manager=deployer -f -

echo "  ConfigMap '${APP_INSTANCE_NAME}-topology-genesis-site-config' applied."

# ---------------------------------------------------------------------------
# 3a-2. Create OpenDSO license secret
#
# Stores the license key and installation key (api_key) as a Kubernetes Secret.
# topology-nodes mounts this via envFrom to get LICENSE_KEY and LICENSE_API_KEY.
# ---------------------------------------------------------------------------
LICENSE_SECRET="${APP_INSTANCE_NAME}-opendso-license"

kubectl create secret generic "$LICENSE_SECRET" \
    --namespace="$NAMESPACE" \
    --from-literal=LICENSE_KEY="${LICENSE_KEY}" \
    --from-literal=LICENSE_API_KEY="${INSTALLATION_KEY}" \
    --from-literal=LICENSE_ENVIRONMENT_NAME="${CLUSTER_ID}" \
    --dry-run=client -o yaml \
  | kubectl apply -f -

echo "  Secret '${LICENSE_SECRET}' applied."

# ---------------------------------------------------------------------------
# 3b. Inject Keycloak client secrets into realm JSON and create K8s secrets
#
# Generates a UUID secret per NATS service client, writes them into the realm
# JSON (so Keycloak imports pre-populated secrets on first boot), and creates
# <release>-<client>-keycloak-env Kubernetes secrets so services can start
# immediately after Helm without any post-install provisioning step.
# ---------------------------------------------------------------------------
echo ""
echo "[3b/3] Injecting Keycloak client secrets..."

# Helm prefers oes-realm-generated.json over oes-realm.json (see site-configmaps.yaml).
# Copy the source (with REPLACE_SECRET_* placeholders) to the generated path so that
# Python writes real UUIDs there and Helm picks up the right file.
REALM_SOURCE="${CHART_DIR}/configs/${SITE}/keycloak/realm/oes-realm.json"
REALM_FILE="${CHART_DIR}/configs/${SITE}/keycloak/realm/oes-realm-generated.json"
cp "${REALM_SOURCE}" "${REALM_FILE}"
KC_EXTERNAL_URL="https://keycloak.${DOMAIN}/realms/oes"
KC_INTERNAL_URL="http://${APP_INSTANCE_NAME}-keycloak-svc:8080/realms/oes"

python3 - "${REALM_FILE}" "${APP_INSTANCE_NAME}" "${NAMESPACE}" "${KC_INTERNAL_URL}" "${KC_EXTERNAL_URL}" << 'PYEOF'
import base64, uuid, subprocess, sys, re

realm_file, release_name, namespace, kc_internal_url, kc_external_url = sys.argv[1:]

with open(realm_file) as f:
    content = f.read()

# Find all REPLACE_SECRET_<client-id> placeholders
placeholders = re.findall(r'REPLACE_SECRET_([\w-]+)', content)

# Reuse existing K8s secret values on re-runs so Keycloak's imported realm stays
# consistent. On first install no secrets exist, so new UUIDs are generated.
secrets = {}
for name in dict.fromkeys(placeholders):
    secret_name = f"{release_name}-{name}-keycloak-env"
    result = subprocess.run(
        ["kubectl", "get", "secret", secret_name, "--namespace", namespace,
         "-o", "jsonpath={.data.KEYCLOAK_CLIENT_SECRET}"],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        secrets[name] = base64.b64decode(result.stdout.strip()).decode()
    else:
        secrets[name] = str(uuid.uuid4())

# Replace placeholders with generated UUIDs
for name, secret in secrets.items():
    content = content.replace(f'REPLACE_SECRET_{name}', secret)

with open(realm_file, 'w') as f:
    f.write(content)

print(f"  Patched {len(secrets)} client secrets in realm JSON")

# Create K8s secrets for each client
errors = 0
for name, secret in secrets.items():
    secret_name = f"{release_name}-{name}-keycloak-env"
    cmd = [
        "kubectl", "create", "secret", "generic", secret_name,
        "--namespace", namespace,
        # Many services use KEYCLOAK_URL as the expected OIDC issuer, so this
        # must match the issuer Keycloak advertises in discovery.
        f"--from-literal=KEYCLOAK_URL={kc_external_url}",
        f"--from-literal=KEYCLOAK_INTERNAL_URL={kc_internal_url}",
        f"--from-literal=KEYCLOAK_EXTERNAL_URL={kc_external_url}",
        f"--from-literal=KEYCLOAK_CLIENT_ID={name}",
        f"--from-literal=KEYCLOAK_CLIENT_SECRET={secret}",
    ]
    # topology-genesis binary has a typo: KEYCLOAD_CLIENT_ID (missing 'A')
    if name == "topology-genesis":
        cmd.append(f"--from-literal=KEYCLOAD_CLIENT_ID={name}")
    cmd += ["--dry-run=client", "-o", "yaml"]
    render = subprocess.run(cmd, capture_output=True, text=True)
    if render.returncode != 0:
        print(f"  WARNING: render failed for {secret_name}: {render.stderr}", file=sys.stderr)
        errors += 1
        continue
    apply = subprocess.run(
        ["kubectl", "apply", "-f", "-"],
        input=render.stdout, capture_output=True, text=True,
    )
    if apply.returncode != 0:
        print(f"  WARNING: apply failed for {secret_name}: {apply.stderr}", file=sys.stderr)
        errors += 1
    else:
        print(f"  Applied {secret_name}")

if errors:
    print(f"  WARNING: {errors} secret(s) failed — check output above", file=sys.stderr)
PYEOF

# ---------------------------------------------------------------------------
# 4. Deploy via Helm
#
# Values precedence (last wins):
#   values-gcp.yaml        — GCP-specific defaults
#   /data/user/values.yaml — user inputs from Marketplace UI (schema.yaml properties)
#   $NATS_AUTH_VALUES      — generated NKey public keys
#   --set overrides        — release-name-dependent values that can't be in values files
# ---------------------------------------------------------------------------
echo ""
echo "[3/3] Running helm upgrade --install..."

# Delete any existing Jobs from this release before upgrading.
# Kubernetes Jobs have immutable specs; Helm cannot patch them on upgrade.
# The mongodb-init job runs once on first install and is idempotent.
kubectl delete jobs \
    "${APP_INSTANCE_NAME}-mongodb-init" \
    -n "$NAMESPACE" \
    --ignore-not-found 2>/dev/null || true

# Adopt any Application resource pre-created by mpdev into Helm management.
# mpdev install creates the Application before the deployer job runs, without
# Helm ownership labels. Without adoption, helm upgrade --install fails with
# "invalid ownership metadata" on the Application resource.
kubectl annotate application.app.k8s.io "$APP_INSTANCE_NAME" \
    -n "$NAMESPACE" \
    "meta.helm.sh/release-name=${APP_INSTANCE_NAME}" \
    "meta.helm.sh/release-namespace=${NAMESPACE}" \
    --overwrite 2>/dev/null || true
kubectl label application.app.k8s.io "$APP_INSTANCE_NAME" \
    -n "$NAMESPACE" \
    "app.kubernetes.io/managed-by=Helm" \
    --overwrite 2>/dev/null || true

helm upgrade --install "$APP_INSTANCE_NAME" "$CHART_DIR" \
    --namespace "$NAMESPACE" \
    --wait \
    --timeout 15m \
    -f "$CHART_DIR/values-gcp.yaml" \
    -f "$USER_VALUES" \
    -f "$NATS_AUTH_VALUES" \
    --set global.keycloak.internalUrl="http://${APP_INSTANCE_NAME}-keycloak-svc:8080" \
    --set global.environment.apiUrl="https://api.${DOMAIN}" \
    --set global.keycloak.url="https://keycloak.${DOMAIN}" \
    --set ingress.tls.secretName="${APP_INSTANCE_NAME}-tls-secret" \
    --set nats.tls.secretName="${APP_INSTANCE_NAME}-tls-secret" \
    --set mongodb.tls.enabled=false \
    --set global.mongodb.tls.enabled=false \
    --set keycloak.tls.enabled=false \
    --set keycloak.config.httpsEnabled=false \
    --set keycloak.config.hostnameStrict=false \
    --set keycloak.config.hostnameStrictHttps=false \
    --set historian-svc.tls.enabled=false \
    --set nats.tls.enabled=false \
    --set grafana.admin.existingSecret="${APP_INSTANCE_NAME}-grafana-credentials" \
    --set "grafana.envValueFrom.CITUS_PASSWORD.secretKeyRef.name=${APP_INSTANCE_NAME}-grafana-credentials" \
    --set "grafana.envValueFrom.OPENDSO_APPS_DB_PASSWORD.secretKeyRef.name=${APP_INSTANCE_NAME}-grafana-credentials" \
    --set global.gcpMarketplace=true \
    ${IMAGE_REGISTRY:+--set global.imageRegistry="${IMAGE_REGISTRY}"}

# ---------------------------------------------------------------------------
# 5. Sync Keycloak client secrets via Admin REST API
#
# Keycloak only imports the realm JSON when starting with an EMPTY database.
# On upgrades or restarts with an existing PVC, realm data (including client
# secrets) is kept from the original import — even if the ConfigMap changed.
#
# This step pushes the *-keycloak-env K8s secret values to Keycloak via the
# Admin API so client secrets are always in sync regardless of deploy history.
# Errors here are non-fatal (logged as WARNINGs); a fresh cluster where Keycloak
# just imported the realm for the first time is already in sync.
# ---------------------------------------------------------------------------
echo ""
echo "[4/4] Syncing Keycloak client secrets via Admin API..."

KC_ADMIN_PASSWORD=$(python3 -c "
import yaml
with open('${USER_VALUES}') as f:
    v = yaml.safe_load(f) or {}
print(v.get('keycloak.config.adminPassword') or v.get('keycloak', {}).get('config', {}).get('adminPassword', 'admin'))
" 2>/dev/null || echo "admin")

KC_INTERNAL="http://${APP_INSTANCE_NAME}-keycloak-svc:8080"

python3 - "${APP_INSTANCE_NAME}" "${NAMESPACE}" "${KC_INTERNAL}" "${KC_ADMIN_PASSWORD}" << 'PYEOF'
import base64, json, subprocess, sys, time, urllib.error, urllib.parse, urllib.request

release_name, namespace, kc_base, admin_password = sys.argv[1:]
realm = "oes"

# Discover *-keycloak-env secrets created by step 3b for this release
result = subprocess.run(
    ["kubectl", "get", "secrets", "-n", namespace,
     "-o", "jsonpath={.items[*].metadata.name}"],
    capture_output=True, text=True,
)
all_names = result.stdout.split() if result.returncode == 0 else []
prefix, suffix = f"{release_name}-", "-keycloak-env"
client_secrets = {}
for s in all_names:
    if s.startswith(prefix) and s.endswith(suffix):
        client_name = s[len(prefix):-len(suffix)]
        r = subprocess.run(
            ["kubectl", "get", "secret", s, "-n", namespace,
             "-o", "jsonpath={.data.KEYCLOAK_CLIENT_SECRET}"],
            capture_output=True, text=True,
        )
        if r.returncode == 0 and r.stdout.strip():
            client_secrets[client_name] = base64.b64decode(r.stdout.strip()).decode()

if not client_secrets:
    print("  No keycloak-env secrets found, skipping sync")
    sys.exit(0)

print(f"  Found {len(client_secrets)} client secret(s) to sync")

# Obtain an admin token (retry up to 60s — Keycloak may need a moment post-start)
def get_token():
    data = urllib.parse.urlencode({
        "client_id": "admin-cli",
        "username": "admin",
        "password": admin_password,
        "grant_type": "password",
    }).encode()
    req = urllib.request.Request(
        f"{kc_base}/realms/master/protocol/openid-connect/token",
        data=data,
        method="POST",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())["access_token"]

token = None
for attempt in range(12):
    try:
        token = get_token()
        break
    except Exception as e:
        if attempt < 11:
            print(f"  Keycloak Admin API not ready yet, retrying... ({e})")
            time.sleep(5)
        else:
            print(f"  WARNING: could not reach Keycloak Admin API: {e}", file=sys.stderr)
            sys.exit(0)

auth_header = {"Authorization": f"Bearer {token}"}

# List all clients in the oes realm
req = urllib.request.Request(
    f"{kc_base}/admin/realms/{realm}/clients?max=200",
    headers=auth_header,
    method="GET",
)
try:
    with urllib.request.urlopen(req, timeout=10) as resp:
        kc_clients = json.loads(resp.read())
except Exception as e:
    print(f"  WARNING: could not list Keycloak clients: {e}", file=sys.stderr)
    sys.exit(0)

kc_id_map = {c["clientId"]: c["id"] for c in kc_clients}

updated, errors = 0, 0
for client_name, secret in client_secrets.items():
    if client_name not in kc_id_map:
        print(f"  WARNING: client '{client_name}' not found in realm '{realm}'", file=sys.stderr)
        errors += 1
        continue
    kc_id = kc_id_map[client_name]
    try:
        # Fetch full client config to avoid clobbering other settings
        req = urllib.request.Request(
            f"{kc_base}/admin/realms/{realm}/clients/{kc_id}",
            headers=auth_header,
            method="GET",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            client_cfg = json.loads(resp.read())
        client_cfg["secret"] = secret
        req = urllib.request.Request(
            f"{kc_base}/admin/realms/{realm}/clients/{kc_id}",
            data=json.dumps(client_cfg).encode(),
            headers={**auth_header, "Content-Type": "application/json"},
            method="PUT",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp.read()  # 204 No Content
        updated += 1
    except Exception as e:
        print(f"  WARNING: failed to update client '{client_name}': {e}", file=sys.stderr)
        errors += 1

print(f"  Synced {updated} client secret(s){f' — {errors} error(s), check output above' if errors else ''}")
PYEOF

patch_assembly_phase.sh --status="Success"
trap - EXIT

echo ""
echo "OpenDSO deployed successfully as release '$APP_INSTANCE_NAME'."

# Clean up temp files
rm -f "$NATS_AUTH_VALUES" "$USER_VALUES"
