apiVersion: v2
name: openfmb-event-creator-app
description: OpenFMB Event Creator Application for OpenDSO
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: OpenDSO Team
    email: info@openenergysolutions.com
