{{- if and (not (and .Values.externalDatabase.enabled .Values.externalDatabase.host)) (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opendso-apps-db.fullname" . }}-secret
  labels:
    {{- include "opendso-apps-db.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "opendso-apps-db auth.password is required when using the in-cluster database" .Values.auth.password | b64enc | quote }}
{{- end }}
