{{- if not (and .Values.externalDatabase.enabled .Values.externalDatabase.host) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opendso-apps-db.fullname" . }}
  labels:
    {{- include "opendso-apps-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "opendso-apps-db.selectorLabels" . | nindent 4 }}
{{- end }}
