replicaCount: 1

image:
  repository: oesinc/topology-genesis
  pullPolicy: IfNotPresent
  tag: "c53cf381"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env:
  PLATFORM_NATS_SERVICE: ""

args:
  - "-c"
  - "/resources/cim.xml"
  - "-e"
  - "/resources/cimex.config"
  - "--db"
  - "/output/cim.db"

configMap:
  name: topology-genesis-configs

persistence:
  enabled: true
  storageClass: ""  # Uses global.storageClass if empty
  accessMode: ReadWriteOnce
  size: 100M
  mountPath: /output

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
