apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats.fullname" . }}-config
  labels:
    {{- include "nats.labels" . | nindent 4 }}
data:
  nats-server.conf: |
    # Client port of 4222 on all interfaces
    port: {{ .Values.service.clientPort }}

    # HTTP monitoring port
    monitor_port: {{ .Values.service.monitorPort }}

    max_payload: 20971520

    websocket: {
      port: {{ .Values.service.websocketPort }}
      {{- if .Values.tls.enabled }}
      tls: {
        cert_file: "/nats/certs/server-cert.pem"
        key_file: "/nats/certs/server-key.pem"
      }
      {{- end }}
      handshake_timeout: "10s"
    }

    server_name: mqtt_passthrough

    jetstream {
       store_dir: datastore
    }

    mqtt {
       port: {{ .Values.service.mqttPort }}
    }

    debug: false
    trace: false

    {{- if .Values.authCallout.enabled }}
    authorization {
      auth_callout {
        issuer: {{ .Values.authCallout.issuer | quote }}
        auth_users: [{{ .Values.authCallout.authUser | quote }}]
        xkey: {{ .Values.authCallout.xkey | quote }}
        account: AUTH
      }
    }

    accounts {
      AUTH {
        users: [{nkey: {{ .Values.authCallout.authUser | quote }}}]
      }
      opendso {}
    }
    {{- end }}
