apiVersion: v2
name: event-viewer-app
description: Event Viewer Application for OpenDSO
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: OpenDSO Team
    email: info@openenergysolutions.com
